#!/bin/bash
#SBATCH -J rdp           # Job name
#SBATCH -o rdp.o%j       # Name of stdout output file
#SBATCH -p gh-dev          # Queue (partition) name
#SBATCH -N 1               # Total # of nodes
#SBATCH -n 1               # Total # of mpi tasks
#SBATCH -t 1:00:00        # Run time (hh:mm:ss)
#SBATCH -A DBS24008       # Allocation name (req'd if you have more than 1)

# Other commands must follow all #SBATCH directives...

source $HOME/.bashrc

module load gcc/13 cuda/12.6 nccl/12.4 #nvidia_math/12.6

conda init

conda activate tsllm

python baselines/rdp/run_rdp_benchmark.py \
  --ckpt_path /scratch/10608/aadharsh_aadhithya/results/rep_lr/results_20250725_111527/run_1/rf_cfo_channel/rf_fingerprinting_cfo_estimation_channel_estimation_20250725_234643/rf_fingerprinting_cfo_estimation_channel_estimation_best.pt \
  --pkl_dataset_path /scratch/10608/aadharsh_aadhithya/data/rep_lr/OracleDatasetProcessed-arranged/rf_partition_dict_0.5.pkl \
  --target_mse_rf 0.500941 \
  --target_mse_cfo 0.345215 \
  --target_mse_channel 0.337255 \
  --gpu_id 0