import os
import sys
import torch
import numpy as np
import pickle
from torch.utils.data import DataLoader

# Add the parent directory to sys.path to import from rep_lr
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from dra_1.py_datasets import ActivationDataset

def _load_partition_data():
    """Helper function to load partition data."""
    # This path is defined in 'code/preprocessing/dataset_partitioner.py'
    # and generated by running that script.
    partition_path = '/home/hofmann/Documents/projects/RepresentationLearning/dataset/rf_partition_dict_0.5.pkl'
    
    if not os.path.exists(partition_path):
        raise FileNotFoundError(
            f"Partition file not found at {partition_path}. "
            "Please run 'code/preprocessing/dataset_partitioner.py' first."
        )
        
    with open(partition_path, 'rb') as f:
        partition_data = pickle.load(f)
        
    # We only need the 'train' split for this test, but you could use 'val' or 'test' too.
    return partition_data.get('train', [])

def test_activation_dataset():
    """Test the ActivationDataset class."""
    print("=" * 50)
    print("Testing ActivationDataset")
    print("=" * 50)
    
    activation_dir = "/home/hofmann/Documents/projects/RepresentationLearning/dataset/activations"
    
    if not os.path.isdir(activation_dir):
        print(f"Warning: Activation directory {activation_dir} does not exist. Skipping tests.")
        print("Please run 'extract_activations.py' to generate activation files.")
        return

    try:
        file_list = _load_partition_data()
        if not file_list:
            print("Warning: No files found in the partition data. Skipping tests.")
            return

        # Create dataset using the file list from the partition
        dataset = ActivationDataset(activation_dir, file_list, test_mode=False)
        print(f"Successfully created dataset with {len(dataset)} files.")
        
        # --- Get a sample and check its properties ---
        if len(dataset) > 0:
            (rf_x, rf_y, cfo_x, cfo_y, 
             channel_x, channel_y, activation, filename) = dataset[0]
            
            print(f"\n--- Sample 0 ---")
            print(f"Original .mat Filename: {filename}")
            print(f"Activation Tensor Shape: {activation.shape}")
            print(f"RF Data Shape: {rf_x.shape}, Label: {rf_y}")
            print(f"CFO Data Shape: {cfo_x.shape}, Label: {cfo_y.item():.4f}")
            print(f"Channel Data Shape: {channel_x.shape}")
            
            # --- Test DataLoader ---
            dataloader = DataLoader(dataset, batch_size=4, shuffle=True)
            batch = next(iter(dataloader))
            (rf_x_b, rf_y_b, cfo_x_b, cfo_y_b, 
             ch_x_b, ch_y_b, act_b, fname_b) = batch
            
            print(f"\n--- DataLoader Batch ---")
            print(f"Batch Activation Shape: {act_b.shape}")
            print(f"Batch RF Data Shape: {rf_x_b.shape}")
            print(f"Batch Filenames: {fname_b}")
            
    except (FileNotFoundError, ValueError) as e:
        print(f"Error during dataset test: {e}")

def test_edge_cases():
    """Test edge cases and error handling."""
    print("\n" + "=" * 50)
    print("Testing Edge Cases")
    print("=" * 50)
    
    activation_dir = "/home/hofmann/Documents/projects/RepresentationLearning/dataset/activations"
    file_list = _load_partition_data()

    # 1. Test with a non-existent activation directory
    try:
        ActivationDataset("/non/existent/path", file_list)
        print("✗ FAIL: Should have raised error for non-existent activation directory.")
    except ValueError as e:
        print(f"✓ PASS: Correctly raised error for non-existent activation directory: {e}")

    # 2. Test with a file_list containing a file not in the activation map
    if file_list:
        try:
            # Add a fake file to the list
            bad_file_list = file_list + ['non_existent_file.mat']
            dataset = ActivationDataset(activation_dir, bad_file_list, test_mode=True)
            # This will fail when __getitem__ is called for the fake file
            dataset[len(dataset)-1] 
            print("✗ FAIL: Should have raised error for missing activation file.")
        except FileNotFoundError as e:
            print(f"✓ PASS: Correctly raised error for missing activation file.")
    
    # 3. Test with an empty file list
    try:
        dataset = ActivationDataset(activation_dir, [])
        assert len(dataset) == 0
        print("✓ PASS: Correctly handled an empty file list.")
    except Exception as e:
        print(f"✗ FAIL: Did not correctly handle an empty file list: {e}")


if __name__ == "__main__":
    print("Starting dataset tests...")
    test_activation_dataset()
    test_edge_cases()
    print("\n" + "=" * 50)
    print("All tests completed!")
    print("=" * 50) 